[all]
k8s-1 ansible_host=192.168.56.11 ip=192.168.56.11 access_ip=192.168.56.11 etcd_member_name=etcd1
k8s-2 ansible_host=192.168.56.12 ip=192.168.56.12 access_ip=192.168.56.12
k8s-3 ansible_host=192.168.56.13 ip=192.168.56.13 access_ip=192.168.56.13

[kube_control_plane]
k8s-1

[etcd]
k8s-1

[kube_node]
k8s-2
k8s-3

[k8s_cluster:children]
kube_control_plane
kube_node

[all:vars]
ansible_user=vagrant
ansible_ssh_private_key_file=~/.vagrant.d/insecure_private_key